# --- Variables en test.http ---
@url = http://127.0.0.1:3000 
@admin_auth = admin_auth_key_secreta 
@user1_pass = Pw12345678# 
@user2_pass = Pw23456789# 
@user1_id = 1 
@user2_id = 2

### 2.1: REGISTRAR Usuario 1 (ID 1)
# Esperado: 201 Created. Documento User creado en MongoDB.
POST {{url}}/users
Content-Type: application/json

{
    "name": "Usuario Test Uno",
    "email": "test1@cineclick.com",
    "password": "{{user1_pass}}",
    "confirm_password": "{{user1_pass}}"
}

### 2.2: PRUEBA DE EXCEPCIÓN: Email Duplicado
# Esperado: 400 Bad Request. Body: "Email already in use."
POST {{url}}/users
Content-Type: application/json

{
    "name": "Usuario Fail",
    "email": "test1@cineclick.com",
    "password": "Pw12345678#",
    "confirm_password": "Pw12345678#"
}

### 3.1: CONSULTA TOTAL (Admin Auth)
# Esperado: 200 OK. JSON con total=1 y data[].
GET {{url}}/users?page=1&limit=5
x-auth: {{admin_auth}}

### 3.2: CONSULTA INDIVIDUAL (Propietario)
# Esperado: 200 OK. Regresa el objeto del Usuario 1.
GET {{url}}/users/1
x-auth: {{user1_pass}}

### 4.1: ACTUALIZAR Nombre del Usuario 1
# Esperado: 200 OK. Regresa el Usuario 1 con el nuevo nombre.
PATCH {{url}}/users/1
x-auth: {{user1_pass}}
Content-Type: application/json

{
    "name": "Usuario Actualizado PATCH"
}

### 4.2: PRUEBA DE EXCEPCIÓN: Autenticación Inválida
# Esperado: 401 Unauthorized. Body: "Unauthorized: Invalid password for this user."
PATCH {{url}}/users/1
x-auth: ContrasenaIncorrecta
Content-Type: application/json

{
    "name": "No debe actualizarse"
}

### 5.1: ELIMINAR Usuario 1
# Esperado: 200 OK. Mensaje de confirmación y el objeto del usuario eliminado.
DELETE {{url}}/users/1
x-auth: {{user1_pass}}